# Generated by Django 5.0.3 on 2024-05-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Candidate',
            new_name='candidate',
        ),
    ]
